### ISSUE TITLE
Problems with accessibility

### ISSUE THREAD

**Issue by jonbrooks** [cxa/MenuItemKit#10]
It seems that VoiceOver will use the `title` of a UIMenuItem as the `accessibilityLabel` unconditionally.  This means a VoiceOver reads "underscore [blah blah] underscore [blah blah] etc..." when you try to use the accessibility features on the Menu.

There doesn't appear to be any way around this issue.  Setting `accessibilityLabel` on a UIMenuItem seems to have no effect.

**Comment by jonbrooks** [comment]
Just to clarify: This is really only a problem with the custom image MenuItems.  The other ones read their titles just like a regular UIMenuItem would.  If there were a way to set the title of the image MenuItems without breaking the swizzling game that's going on here, there would be no problem.

**Comment by cxa** [comment]
Custom image menu item is rely on the “nonsense” unique hidden title, I'll in investigate other ways but I can't promise.
