### ISSUE TITLE
CocoaPods Owner

### ISSUE THREAD

**Issue by alexpopov** [cxa/MenuItemKit#12]
Hey Chen, 

I've implemented CocoaPods support, but I had to set myself as the owner. That's obviously not fair, since you're the owner, so if you could, please follow these steps to set yourself as the owner of the pod 😊 

https://guides.cocoapods.org/making/getting-setup-with-trunk.html#adding-other-people-as-contributors

I will add CocoaPods/Carthage support to the README soon.

**Comment by cxa** [comment]
Hi Alex,

I've registered a CocoaPods account with xianan.chen AT gmail.com, simply add me as contributor with this account. It's OK to me since I don't have time to reclaim ownership. Thanks for your work.

**Comment by muhrifqii** [comment]
Any updates for using CocoaPod?

**Comment by cxa** [comment]
No problems on CocoaPod: https://cocoapods.org/pods/MenuItemKit
