### ISSUE TITLE
CocoaPods support not working

### ISSUE THREAD

**Issue by hsen-dev** [cxa/MenuItemKit#14]
`Error: 
no visible @interface for 'UIMenuItem' declares the selector 'mik_initWithTitle:image:action:'`

**Comment by cxa** [comment]
Check if you are using the latest version.

**Comment by hsen-dev** [comment]
I use CocoaPods and updated it.
https://cocoapods.org/?q=MenuItemKit
Latest version in cocoapods is 1.0.1

**Comment by hsen-dev** [comment]
I guess [CocoaPods Specs](https://github.com/CocoaPods/Specs/blob/master/Specs/MenuItemKit/1.0.1/MenuItemKit.podspec.json) is out of date. Your repo latest version is [1.1.2](https://github.com/cxa/MenuItemKit/releases/tag/1.1.2)

**Comment by hsen-dev** [comment]
I use **MenuItemKit** in Obj-C code;

**Comment by cxa** [comment]
I've pushed 1.1.2 to CocoaPods, please try again.

**Comment by themcaguy** [comment]
@cxa I am using the latest framework version 4.0.0 (https://github.com/cxa/MenuItemKit/releases/latest) but facing the same issue, Can you please help me? I am using this in a ObjectiveC project.

**Comment by cxa** [comment]
> @cxa I am using the latest framework version 4.0.0 (https://github.com/cxa/MenuItemKit/releases/latest) but facing the same issue, Can you please help me? I am using this in a ObjectiveC project.

Hi, I've tested the 4.0.0 but found no problem. Maybe you should reset your project.
