### ISSUE TITLE
Not able to add menu item with Image for Webview

### ISSUE THREAD

**Issue by saleelkarkhanis** [cxa/MenuItemKit#21]
I am trying ti add Image as UIMenuItem for my Webview using this library.
this works well when i use xcode 8.x but it fails when i use Xcode 9.0 and application hangs.

Any help?

**Comment by cxa** [comment]
Could you post a sample project?

**Comment by saleelkarkhanis** [comment]
Hey actully i am able to get it working now but now the problem is 'CanPerFormSelector' is not getting called for my custom selectors. can you help?
