### ISSUE TITLE
How to check MenuItem Actions in CanPerformAction Method

### ISSUE THREAD

**Issue by saleelkarkhanis** [cxa/MenuItemKit#22]
How can i check MenuItem Actions in CanPerformAction Method because they are not selectors

**Comment by cxa** [comment]
For now, only can tell if the selector belongs to MenuItemKit, using the static method`isMenuItemKitSelector` in `UIMenuItem`.

**Comment by saleelkarkhanis** [comment]
Ok. Will check that. Actully CanPerformSelector method is not getting called for custom selectors. I have tried to log all the actions but its not showing my custom Actions.
Any help on That?
EDIT: I am not getting how to use this isMenuItemKitSelector
