### ISSUE TITLE
canPerformAction Method not getting called for custom selectors

### ISSUE THREAD

**Issue by saleelkarkhanis** [cxa/MenuItemKit#23]
Hi Following is the way i am creating custom MenuItems

let menuController = UIMenuController.shared
let redImageItem = UIMenuItem(title: Highlight.redColor.rawValue, image: imageWithColor(Highlight.redColor.getColor())!) { [weak self] (item) in
            self?.setRedColor()
}

But when i log all the actions in canPerformAction method, i cant find one for this Menu Item.
How can i check this?

**Comment by cxa** [comment]
try add `canBecomeFirstResponder` and return `true` to your view controller.

**Comment by saleelkarkhanis** [comment]
Thanks for the suggession but i am still not able to see it.
cut:
Actions ---- copy:
Actions ---- select:
Actions ---- selectAll:
Actions ---- paste:
Actions ---- delete:
Actions ---- _promptForReplace:
Actions ---- _transliterateChinese:
Actions ---- _insertDrawing:
Actions ---- _showTextStyleOptions:
Actions ---- _lookup:
Actions ---- _define:
Actions ---- _addShortcut:
Actions ---- _accessibilitySpeak:
Actions ---- _accessibilitySpeakLanguageSelection:
Actions ---- _accessibilityPauseSpeaking:
Actions ---- _share:
Actions ---- makeTextWritingDirectionRightToLeft:
Actions ---- makeTextWritingDirectionLeftToRight:

This is the list of Actions i am getting in CanPerformAction when i select the text.
Note: I am using a Webview here

**Comment by cxa** [comment]
Have you ever set `menuItems` to `UIMenuController`?

**Comment by saleelkarkhanis** [comment]
Yes. 
menuController.menuItems = [redImageItem, yellowImageItem, greenImageItem, blueImageItem, pinkImageItem, whiteImageItem, grayImageItem]
menuController.setTargetRect(getSelectedTextRect(), in: self)
menuController.setMenuVisible(true, animated: true)

**Comment by cxa** [comment]
You may need to subclass UIWebView and override `canPerformAction(_:withSender:)`.

**Comment by saleelkarkhanis** [comment]
Yes I have done the same thing. 
Earlier i was using "UIMenuItem-CXAImageSupport" and it was working perfect with canPerformAction. 
Now it started breaking on Xcode 9 and hence i have moved to "MenuItemKit"

**Comment by cxa** [comment]
Here is a working example.

[WebViewMenu.zip](https://github.com/cxa/MenuItemKit/files/1387179/WebViewMenu.zip)

**Comment by cxa** [comment]
Seems there has some issues on webview. Will investigate when I have time.

**Comment by saleelkarkhanis** [comment]
@cxa  Any Update on this ? Did you get any chance to look into it?

**Comment by cxa** [comment]
Check `UIMenuController.installTo(responder:shouldShowForAction:)` in latest release, also there is an example in the repo.
