### ISSUE TITLE
Unable to get image menu in case of wkwebview

### ISSUE THREAD

**Issue by devanshu2** [cxa/MenuItemKit#24]
Hi
I initialized custom menu on view did load with a controller having wkwebview. I am unable to add up these custom menus although I am able to see the default type UIMenuItem say I add up "ABC"
Help

**Comment by raulferrerdev** [comment]
Is there a problem with the use of MenuItemKit with WKWebView? Items added (text and/or images) don't appear in the menu.
Tested on UIWebView and didn't work either.

**Comment by raulferrerdev** [comment]
UPDATE
@devanshu2 Problem solved! The issue is related with UIRespoder. To show icons on menu, first webpage must be fully loaded, the set webview as primary responder an then, set the new menu controller:

```
extension CustomViewController: WKNavigationDelegate, WKUIDelegate {
    
   func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        // Web page has complete loaded
        webview.becomeFirstResponder()

        // Set menu
        let menu = UIMenuController.shared
        let firstItem = UIMenuItem(title: "Item1", image: (UIImage(name: "image1"), action: { _ in 
            print("First item")
        })
        let secondItem = UIMenuItem(title: "Item2", image: (UIImage(name: "image2"), action: { _ in 
            print("Second item")
        })
        let thirdItem = UIMenuItem(title: "Item3", image: (UIImage(name: "image3"), action: { _ in 
            print("Third item")
        })

        menu.menuItems = [firstItem, secondItem, thirdItem]
    }
}
```

**Comment by devanshudew** [comment]
@dev-journey Thanks

**Comment by cxa** [comment]
Seems resolved, close now. Reopen in any doubt.
