### ISSUE TITLE
Crash: Unrecognized selector sent to instance for custom action

### ISSUE THREAD

**Issue by lpbas** [cxa/MenuItemKit#26]
Hello. I;'m trying to use this great kit for my custom menu actions, but unfortunately if I add the actions and do not show the menu on a particular button click, My app crashes when any custom action is pressed with the following exception:

` -[UITextView _menuitemkit_block_6BB2EFBD_033E_4144_9AF4_1D7FB291ED08:]: unrecognized selector sent to instance 0x7fbdc5079600`

I'm trying to add some functions to a TextView's popup menu (not a menu I set visible by hand), so in my VC's viedDidload I do the following:

```swift
func setupEditMenu() {
	let controller = UIMenuController.shared

	controller.arrowDirection = .default
	controller.setTargetRect(articleView.bodyTextView.frame, in: self.view)

	let action: MenuItemAction = { [weak self] menuItem in
		self?.highlightTapped( (menuItem.title as NSString).integerValue) 
        }

	let yellow = UIMenuItem(title: "1", image: #imageLiteral(resourceName: "hl_yellow"), action: action)
	let orange = UIMenuItem(title: "2", image: #imageLiteral(resourceName: "hl_orange"), action: action)
	let green = UIMenuItem(title: "3", image: #imageLiteral(resourceName: "hl_green"), action: action)
	let pink = UIMenuItem(title: "4", image: #imageLiteral(resourceName: "hl_pink"), action: action)
	let blue = UIMenuItem(title: "5", image: #imageLiteral(resourceName: "hl_blue"), action: action)

	controller.menuItems = [yellow, orange, green, pink, blue]
	controller.update()
}

```

and when one of the above actions gets selected I get the exception above. However, if I call setupEditMenu when a button is pressed, all the actions work fine, even when the menu is presented by the TextView.

`highlightTapped` is a function below that gets an int value and highlights my text depending on that value.

I'm assuming this is a bug on UIMenuKit and how the selectors are generated for each action. Any Idea why this is happening and how to fix it or a workaround. I want the menu to be presented automatically when the user selects text inside the TextView, not when a button is pressed.

Any help will be greatly appreciated. Thank you very much!

**Comment by cxa** [comment]
Try the new release and use `UIMenuController.installTo(responder:shouldShowForAction:)`, see the `AutoPopupMenuContorllerDemo` for detail.

**Comment by lpbas** [comment]
Perfect! Thank you so much!!! 👏🏼👏🏼👏🏼
