### ISSUE TITLE
Crash when run it without connecting to Xcode

### ISSUE THREAD

**Issue by magicboker** [cxa/MenuItemKit#28]
```
in Swizzlings.m

+ (void)load
{
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    for (id klass in @[[UIMenuController class], [UILabel class], [NSString class]]) {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Warc-performSelector-leaks"
      [klass performSelector:NSSelectorFromString(@"_mik_load")]; // <---- crash if this line is not comment out
#pragma clang diagnostic pop
    }
  });
}
```

**Comment by magicboker** [comment]
it happen since Xcode 9.3 using swift 4.1

**Comment by cxa** [comment]
Any bug-reproducible project for testing? I tested the Demo project with  Xcode 9.3/Swift 4.1 but found no problem.

**Comment by magicboker** [comment]
It's weird it only happened in my projects

![a crash log](https://magicboker.github.io/menuitemkit_crash.png)

MenuItemKit was included as a embedded framework so the core dump seemed cannot resolve the symbols. any idea to fix this?

**Comment by cxa** [comment]
Seems like your app failed to embed MenuItemKit in release build? Try remove and add again.

**Comment by magicboker** [comment]
I re-added the framework and still crashed.

I did some experiments in Internals.swift and found it crashed in "imp_implementationWithBlock"

```
func setNewIMPWithBlock<T>(_ block: T, forSelector selector: Selector, toClass klass: AnyClass) {
  let method = class_getInstanceMethod(klass, selector)
  let imp = imp_implementationWithBlock(unsafeBitCast(block, to: AnyObject.self)) // <---- crash here!
  if !class_addMethod(klass, selector, imp, method_getTypeEncoding(method!)) {
    method_setImplementation(method!, imp)
  }
}
```

**Comment by cxa** [comment]
So you set a nil block?

**Comment by magicboker** [comment]
no, i didn't change any other part to find which line caused the crash

**Comment by magicboker** [comment]
It's not a "release" build, but a "debug" build.

However, it only crash when running it without using XCode.

**Comment by cxa** [comment]
Could you run our demo example to see if that also happen on your device?

**Comment by magicboker** [comment]
I ran demo example without a problem.

However, i found the root cause was the objective-c +load (Swizzlings.m) timing. When it's called, some other swift classes were not loaded. I started a timer to delay the execution of "[klass performSelector:NSSelectorFromString(@"_mik_load")];" , and then it went through well. 

It seems the timing of objective-c +load method is dynamic and problematic for swizzling because not all swift classes are loaded yet and cause EXC_BAD_ACCESS in the setNewIMPWithBlock function.

**Comment by magicboker** [comment]
Do you have any better idea to workaround it ?
otherwise, I suggest to "Implement method swizzling in the app delegate" as this article mentioned:
http://nshipster.com/swift-objc-runtime/

**Comment by cxa** [comment]
This is why I used ObjC load, that can be sure to run.

Version 3.1.2 should fix this issue, please give it a try.

**Comment by magicboker** [comment]
Thanks, the latest version, 3.1.2, works well!

**Comment by cxa** [comment]
Great to hear it works! Thanks for your feedback.
