### ISSUE TITLE
 select all, copy, paste text menu gets added when textfield is first responder and menu tapped.

### ISSUE THREAD

**Issue by prakashmaharjan** [cxa/MenuItemKit#29]
When using, if text field is tapped then, the other options like select all, copy, paste text menu gets added in the menu and my added options moves to right with arrow option. How to disable those options to not add in menu?

<img width="329" alt="screen shot 2018-04-20 at 7 17 26 pm" src="https://user-images.githubusercontent.com/8100150/39053765-87312696-44cf-11e8-9c04-4ff3320ebd1d.png">

**Comment by cxa** [comment]
Try this approach: https://github.com/cxa/MenuItemKit/blob/d5382af85fc15aae5a78defb97db50f054e93a8f/AutoPopupMenuContorllerDemo/AutoPopupMenuContorllerDemo/ViewController.swift#L36

**Comment by cxa** [comment]
Close due to inactivity.
