### ISSUE TITLE
error on call `installTo` servalTimes

### ISSUE THREAD

**Issue by starFelix** [cxa/MenuItemKit#31]
if call the `installTo` servalTimes, you will find `self` which was catched by block still the same one.
And I found that, the `installTo` was hooked once. It made that if you call the `installTo` servalTimes, the action wouldn't be invoked at all.

**Comment by starFelix** [comment]
no answer, and it's closed....what?

**Comment by cxa** [comment]
Sorry this is auto closed by git commit, I though it should be answered. The new release fixed this issue: https://github.com/cxa/MenuItemKit/releases/tag/3.2.1

**Comment by starFelix** [comment]
thanks!
