### ISSUE TITLE
pod update can't reach 4.0.1

### ISSUE THREAD

**Issue by dan12411** [cxa/MenuItemKit#34]
Because .podspec file not update yet, so pod update can't reach 4.0.1: 
https://github.com/CocoaPods/Specs/tree/master/Specs/5/e/4/MenuItemKit

Ref: https://sebastiandobrincu.com/blog/how-to-update-your-cocoapods-library-version

**Comment by cxa** [comment]
Sorry, I forgot to push 4.0.1 again after fail twice due to bad network here. I've managed to push anyway.
