### ISSUE TITLE
Images getting cropped out

### ISSUE THREAD

**Issue by WeiMin-M** [cxa/MenuItemKit#36]
Hello, thank you for this great kit, i have used the sample code in the demo. It works for me but there is just one issue, the images get cut out at the bottom and top. I have tried adding padding to the image height itself, but it doesn't make the menu taller. Is there any way to make the menu height bigger to fit the whole image? Thank you.

**Comment by cxa** [comment]
The height of each menu item is fixed, not possible to change as I know.

**Comment by WeiMin-M** [comment]
Ahh, if so is it possible to just get the height of the menu controller in a way to just allow me to have a size to resize my images to? Much thanks!

**Comment by cxa** [comment]
Here is the code to draw the image: https://github.com/cxa/MenuItemKit/blob/master/MenuItemKit/Swift/Swizzlings.swift#L188-L199

The simple way maybe adjust your image size manually to fit the menu item.

**Comment by cxa** [comment]
Close due to inactivity.
