### ISSUE TITLE
iOS 16 support

### ISSUE THREAD

**Issue by Igor-Palaguta** [cxa/MenuItemKit#39]
MenuItemKit does not properly work on iOS 16, sometimes it shows the same items, sometimes it crashes

<img width="126" alt="Screenshot 2022-06-15 at 11 46 19" src="https://user-images.githubusercontent.com/800044/173798039-8b23fb8b-342f-46ab-b8a7-c0a48f13efea.png">

**Comment by do784208** [comment]
You can try it.
https://developer.apple.com/documentation/uikit/uieditmenuinteraction

**Comment by alexliubj** [comment]
@cxa 
Can you please add official update for iOS 16

@Igor-Palaguta Any update from your side?

**Comment by cxa** [comment]
UIMenuController is deprecated. Use UIEditMenuInteraction instead.

This project's life comes to its end.
