### ISSUE TITLE
IOS 10 - All the coloured images are became white

### ISSUE THREAD

**Issue by shahaf** [cxa/MenuItemKit#9]
Hi,
I've tested my app in iOS 10 beta and found that the menu items became white:
# Before:

![2118de68-3d64-11e6-9fb5-81bc121ecbeb](https://cloud.githubusercontent.com/assets/840778/16545064/971cee54-4126-11e6-969b-2dfca519d901.png)
# And now with iOS 10 this look like the following:

![3af3c528-3d64-11e6-81cf-e222572e3a68](https://cloud.githubusercontent.com/assets/840778/16545065/9ff3cdea-4126-11e6-8fe4-ae7d4620d649.png)

Thanks in advance

**Comment by cxa** [comment]
Have no idea yet. Wait for some few beta SDKs.

**Comment by jfahrenkrug** [comment]
I debugged this a bit. The CGBitmapContext is different on iOS 10 when drawing the title of a UIMenuItem. It is configured with `kCGImageAlphaOnly`. A somewhat ugly workaround I came up with is to actually add UIImageView subviews like so in the swizzled `drawTextInRect:` (this is Obj-C code):

```
    UIImageView *imageView = [[UIImageView alloc] initWithImage:img];
    [self.superview addSubview:imageView];
    imageView.contentMode = UIViewContentModeCenter;
    imageView.frame = self.superview.bounds;
    imageView.translatesAutoresizingMaskIntoConstraints = NO;
    imageView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
```

(This applies to the old UIMenuItem+CXAImageSupport project)

**Comment by shahaf** [comment]
Thank you Jfahrenkrug.

**Comment by jfahrenkrug** [comment]
@cxa Thank you for the fix, but do you think it's safe to access the private "_button" ivar of the UILabel? That seems very brittle plus it might not make it through the App Store review.

**Comment by cxa** [comment]
@jfahrenkrug The code is safe for running. I'm not sure it's safe for App Store review or not, but I think the API checker will pass the "_button".

**Comment by raulferrerdev** [comment]
@cxa @jfahrenkrug I agree that "_button" won't pass App Store review. Maybe, as @jfahrenkrug pointed, adding a UIImageView will do the work, modifying:

```
// Workaround for #9: https://github.com/cxa/MenuItemKit/issues/9
let point = CGPoint(
    x: (rect.width  - image.size.width)  / 2,
    y: (rect.height - image.size.height) / 2)
if let btn = label.valueForKey("_button") as? UIButton {
     btn.setImage(image, forState: .Normal)
     btn.imageView?.frame.origin = point
} else {
     image.drawAtPoint(point)
}
```

with:

```
// Workaround for #9: https://github.com/cxa/MenuItemKit/issues/9
let point = CGPoint(
    x: (rect.width  - image.size.width)  / 2,
    y: (rect.height - image.size.height) / 2)

let imageView = UIImageView(image: image)
imageView.frame.origin = point
label.addSubview(imageview)
```

**Comment by trivedidurgesh** [comment]
@jfahrenkrug Thank you for the fix suggested on UIMenuItem+CXAImageSupport project.  I was using the old Lib in my project. Which is the objective C code .

**Comment by trivedidurgesh** [comment]
@cxa this lib is really  amazing thanks for creating it.
